//
//  Alarma.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Alarma: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _aLARMAID: String?
    var _aLARMAOFF: String?
    var _aLARMAON: String?
    var _dTREG: String?
    
    class func dynamoDBTableName() -> String {

        return "comrudyllantoysmartp-mobilehub-576705720-Alarma"
    }
    
    class func hashKeyAttribute() -> String {

        return "_aLARMAID"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_aLARMAID" : "ALARMAID",
               "_aLARMAOFF" : "ALARMA_OFF",
               "_aLARMAON" : "ALARMA_ON",
               "_dTREG" : "DT_REG",
        ]
    }
}
