//
//  Coneccion.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Coneccion: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _cONNID: String?
    var _cONNOFF: String?
    var _cONNON: String?
    var _dTREG: String?
    
    class func dynamoDBTableName() -> String {

        return "comrudyllantoysmartp-mobilehub-576705720-Coneccion"
    }
    
    class func hashKeyAttribute() -> String {

        return "_cONNID"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_cONNID" : "CONN_ID",
               "_cONNOFF" : "CONN_OFF",
               "_cONNON" : "CONN_ON",
               "_dTREG" : "DT_REG",
        ]
    }
}
